name = "cdn-manager-worker"
main = "src/index.ts"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "./public"

[vars]
GITHUB_USER = ""
GITHUB_REPO = ""
GITHUB_BRANCH = "main"

[[d1_databases]]
binding = "DB"
database_name = "cdn_manager_db"
database_id = "PREENCHIDO_PELO_DEPLOY_BUTTON"
preview_database_id = "DB"
